name = "MxxGadgets"
version = "0.1.0"
defaultTargets = ["MxxGadgets"]

[leanOptions]
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
path = "../../backends/lean/.lake/packages/mathlib"

[[require]]
name = "MxxBackends"
path = "../../backends/lean"

[[lean_lib]]
name = "MxxGadgets"
roots = [
  "GadgetsDecomposition",
  "GadgetsGadgetMatrix",
  "MxxGadgets",
]
