name = "mxx-runtime"
version = "0.1.0"
defaultTargets = ["MxxRuntime"]

[leanOptions]
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "MxxIrCore"
path = "../../ir-core/lean"

[[require]]
name = "MxxPrimitives"
path = "../../primitives/lean"

[[lean_lib]]
name = "MxxRuntime"
