name = "MxxKhe"
version = "0.1.0"
defaultTargets = ["MxxKhe"]

[leanOptions]
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
path = "../../ir-core/lean/.lake/packages/mathlib"

[[require]]
name = "mxx-ir-core"
path = "../../ir-core/lean"

[[lean_lib]]
name = "MxxKhe"
roots = [
  "BggEncoding",
  "BggMultiplication",
  "GadgetsDecomposition",
  "GadgetsGadgetMatrix",
  "MxxKhe",
]
