//! Frozen-IR fixtures with Lean proofs, generated by ordinary unit tests.

mod constant;
mod gadget;
mod hash;
mod identifiers;
mod loop_binding;
mod loops;
mod matrix_ops;
mod preimage;
mod sampler;

fn write_fixture(name: &str, source: String) {
    let directory = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../test_data/lean_ir_fixtures")
        .join(name);
    std::fs::create_dir_all(&directory).expect("create fixture directory");
    std::fs::write(directory.join("Generated.lean"), source).expect("write Lean fixture");
}
