[package]
name = "mxx-io"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Indistinguishability obfuscation constructions for mxx"

[features]
default = []
gpu = ["mxx-primitives/gpu", "mxx-gadgets/gpu", "mxx-runtime/gpu"]

[dependencies]
mxx-bgg.workspace = true
mxx-dsl.workspace = true
mxx-gadgets.workspace = true
mxx-ir-core.workspace = true
mxx-ir-symbolic.workspace = true
mxx-noise-simulator.workspace = true
mxx-primitives.workspace = true
mxx-runtime.workspace = true
bigdecimal.workspace = true
digest.workspace = true
keccak-asm.workspace = true
num-bigint.workspace = true
rand.workspace = true
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
mxx-primitives = { workspace = true, features = ["test-gpu-sync"] }
mxx-gadgets.workspace = true
